apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-testmsmqwebdisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-testmsmqwebdisk
  storageClassName: managed-csi