apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmsmqweb
  labels:
    app: testmsmqweb
spec:
  replicas: 1
  template:
    metadata:
      name: testmsmqweb
      labels:
        app: testmsmqweb
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: testmsmqweb
        image: dockerdevsampleacr.azurecr.io/testmsmqweb:latest
        resources:
          limits:
            cpu: 1
            memory: 2048M
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: c:\home
          name: testmsmqweb-home
      volumes:
      - name: testmsmqweb-home
        persistentVolumeClaim:
          claimName: pvc-testmsmqwebdisk
  selector:
    matchLabels:
      app: testmsmqweb
---
apiVersion: v1
kind: Service
metadata:
  name: testmsmqweblb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: testmsmqweb