apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-testmsmqwebdisk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/6f4fe300-6d89-4272-8aa9-223e28d46391/resourceGroups/pfad-aks-rg/providers/Microsoft.Compute/disks/pfadtestmsmqwebdisk
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-testmsmqwebdisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-testmsmqwebdisk
  storageClassName: managed-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testmsmqweb
  labels:
    app: testmsmqweb
spec:
  replicas: 1
  template:
    metadata:
      name: testmsmqweb
      labels:
        app: testmsmqweb
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: testmsmqweb
        image: dockerdevsampleacr.azurecr.io/testmsmqweb:latest
        resources:
          limits:
            cpu: 2
            memory: 2048M
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: /home
          name: testmsmqweb-home
      volumes:
      - name: testmsmqweb-home
        persistentVolumeClaim:
          claimName: pvc-testmsmqwebdisk
  selector:
    matchLabels:
      app: testmsmqweb
---
apiVersion: v1
kind: Service
metadata:
  name: testmsmqweblb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: testmsmqweb